---
- name: Install git
  become: true
  dnf:
    name:
      - git
      - gh
    state: present

- name: Linking configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link

- name: Linking configuration dir
  ansible.builtin.file:
    src: "{{ role_path }}/files/git"
    dest: "{{ xdg_config_home }}/git"
    state: link
