---
- name: Install tmux
  become: true
  dnf:
    name: tmux
    state: present

- name: Linking tmux configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    state: link
