---
- name: Installing developer tools
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - g++
      - gdb
      - ninja-build
      - ccache
      - cmake
      - meson
      - conan
      - mold
    state: present

- name: Installing developer tools (flatpak)
  community.general.flatpak:
    name:
      - org.kde.kcachegrind
      - org.kde.massif-visualizer
    state: present

- name: Set default linker to mold
  become: true
  community.general.alternatives:
    name: ld
    path: /usr/bin/ld.mold
    state: present
