---
- name: install syncthing
  become: true
  dnf:
    name:
      - syncthing
    state: present

- name: enable linger
  command: "loginctl enable-linger {{ the_user }}"

- name: create user systemd directory
  file:
    path: "{{ xdg_config_home }}/systemd/user"
    state: directory

- name: link service file
  file:
    src: "{{ role_path }}/files/syncthing.service"
    dest: "{{ xdg_config_home }}/systemd/user/syncthing.service"
    state: link

- name: enable systemd service
  systemd:
    name: syncthing
    scope: user
    enabled: true
    state: started
